kind: Namespace
apiVersion: v1
metadata:
  name: roboshop
---
# this role is admin role fo roboshop project beacuase we are alowwing eerything hear namespace level access
# role is for namespace level access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
# role was created need to bind with the user
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: robodhop
subjects:
# You can specify more than one "subject"
- kind: User
  name: saivinay # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: roboshop-adminr # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io